### ISSUE TITLE
Paho Arduino package has changed, download link no longer works

### ISSUE THREAD

**Issue by icraggs** [ibm-messaging/iot-arduino#1]
The link to the Paho Arduino MQTT client package has changed.    It's probably best to link to this downloads page: https://projects.eclipse.org/projects/technology.paho/downloads, as that will always point to the latest level.

Secondly, the name of one of the headers has changed.  EthernetStack.h is now called IPStack.h.  Now the package has reached the 1.0 level, such name changes should no longer happen.

**Comment by amitmangalvedkar** [comment]
This has been fixed.
