### ISSUE TITLE
Missing information in "Registered Flow from device and to device" section

### ISSUE THREAD

**Issue by istrate** [ibm-messaging/iot-arduino#13]
Should this 

3. Modify the CLIENT_ID, in the sketch code, by providing the values in the following format "d:uguhsp:iotsample-arduino:00aabbccde03", by replacing "aabbccde03" with the MAC Address and "uguhsp" with the organization

be replaced with this

3. Modify the CLIENT_ID, in the sketch code, by providing the values in the following format "d:uguhsp:iotsample-arduino:00aabbccde03", by replacing "aabbccde03" with the MAC Address,  "uguhsp" with the organization, **and "iotsample-arduino" with the device type that you entered when creating the device.**

in **Registered Flow from device and to device** section

**Comment by amitmangalvedkar** [comment]
Thats right and we will change the documentation to reflect the same.
