### ISSUE TITLE
(Minor) The CLIENT_ID and MS_PROXY values from registered.ino may not be clear enough

### ISSUE THREAD

**Issue by OscarAlmgren** [ibm-messaging/iot-arduino#7]
Aiding a developer (from Arduino!) in getting a UNO device up and running, the code is populated by another IoTF MS_PROXY and CLIENT_ID.

It would be preferable to have these values like <your_org>, <device_type>, <device_id> to force a developer to update these values if they're scanning for places to update values.

**Comment by amitmangalvedkar** [comment]
Hi Oscar,
I believe this is what you meant
#define CLIENT_ID 
#define MS_PROXY 
i.e. leaving the values blank
However, this would throw compilation errors and would confuse the end-user further. That is why in the documentation I have provided steps 2 and 3 in https://github.com/ibm-messaging/iot-arduino, wherein I explain how we need to modify the values.

Thanks and Regards
Amit M Mangalvedkar
